// Generated by CoffeeScript 1.6.3
(function() {
  var api, assert, base_url, slumber;

  assert = require('assert');

  slumber = require('..');

  base_url = 'http://www.example.com/';

  api = slumber.API(base_url, {}, function() {});

  describe('Routing', function() {
    describe('#base_url', function() {
      return it('should retrieve a string with base_url of api', function() {
        return assert.equal(api.base_url, base_url);
      });
    });
    describe('one child', function() {
      return it('should retrieve a string with base_url of api with 1 child', function() {
        return assert.equal(api('customers').base_url, "" + base_url + "customers/");
      });
    });
    return describe('two children', function() {
      return it('should retrieve a string with base_url of api with 2 children', function() {
        return assert.equal(api('customers')(42).base_url, "" + base_url + "customers/42/");
      });
    });
  });

}).call(this);
