// Generated by CoffeeScript 1.6.3
(function() {
  var API, append_slash, callable, debug, request, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  debug = require('debug')('slumber:api');

  _ref = require('./utils'), callable = _ref.callable, append_slash = _ref.append_slash;

  request = require('request');

  API = callable((function() {
    function _Class(base_url, opts, fn) {
      var _base, _base1, _base2, _base3, _base4;
      this.opts = opts != null ? opts : {};
      if (fn == null) {
        fn = null;
      }
      this.get = __bind(this.get, this);
      this._request = __bind(this._request, this);
      this._try_to_serialize = __bind(this._try_to_serialize, this);
      this._create_child = __bind(this._create_child, this);
      debug("constructor base_url=" + base_url);
      if (base_url != null) {
        this.opts.base_url = base_url;
      }
      if ((_base = this.opts).append_slash == null) {
        _base.append_slash = true;
      }
      if ((_base1 = this.opts).session == null) {
        _base1.session = null;
      }
      if ((_base2 = this.opts).auth == null) {
        _base2.auth = null;
      }
      if ((_base3 = this.opts).format == null) {
        _base3.format = 'json';
      }
      if ((_base4 = this.opts).serializer == null) {
        _base4.serializer = null;
      }
      if (this.opts.append_slash) {
        this.opts.base_url = append_slash(this.opts.base_url);
      }
      this.base_url = this.opts.base_url;
      if (!this.opts.base_url) {
        throw "base_url is required";
      }
      process.nextTick(function() {
        if (fn) {
          return fn(this);
        }
      });
      return this;
    }

    _Class.prototype._create_child = function(path) {
      var callable_api, child, new_base_url;
      new_base_url = "" + (append_slash(this.base_url)) + path;
      callable_api = API;
      child = new callable_api(new_base_url, this.opts);
      return child;
    };

    _Class.prototype._try_to_serialize = function(response, body) {
      return body;
    };

    _Class.prototype._request = function(method, args, fn) {
      var req, request_options;
      debug("" + method, args);
      request_options = {
        url: this.base_url,
        method: method
      };
      return req = request(request_options, fn);
    };

    _Class.prototype.callable = _Class.prototype._create_child;

    _Class.prototype.get = function() {
      var args, fn, handle, resp, _i,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), fn = arguments[_i++];
      handle = function(err, response, body) {
        var _ref1;
        console.log(response.statusCode);
        if ((200 <= (_ref1 = response.statusCode) && _ref1 <= 299)) {
          return fn(err, _this._try_to_serialize(response, body));
        } else {
          return fn(true);
        }
      };
      return resp = this._request('GET', args, handle);
    };

    _Class.prototype.post = function() {
      return debug('post', this.base_url);
    };

    _Class.prototype.patch = function() {
      return debug('path');
    };

    _Class.prototype.put = function() {
      return debug('put');
    };

    _Class.prototype["delete"] = function() {
      return debug('delete');
    };

    return _Class;

  })());

  module.exports = API;

}).call(this);
