// Generated by CoffeeScript 1.6.3
(function() {
  var RessourceAttributesMixin, debug,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  debug = require('debug')('slumber:Ressource');

  RessourceAttributesMixin = require('./RessourceAttributesMixin').RessourceAttributesMixin;

  module.exports.Ressource = (function(_super) {
    __extends(Ressource, _super);

    function Ressource() {
      debug('constructor');
      Ressource.__super__.constructor.apply(this, arguments);
      return this.getattr;
    }

    return Ressource;

  })(RessourceAttributesMixin);

}).call(this);
