// Generated by CoffeeScript 1.6.3
(function() {
  var callable, debug, getattr,
    __slice = [].slice;

  debug = require('debug')('slumber:RessourceAttributesMixin');

  "use strict";

  callable = function(ctor) {
    var callable_ctor, _ref;
    callable_ctor = function() {
      var a, obj, result;
      a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      obj = function() {
        return obj.callable.apply(typeof this !== "undefined" && this !== null ? this : obj, arguments);
      };
      obj.__proto__ = ctor.prototype;
      result = ctor.call(obj);
      if (typeof result === 'object') {
        return result;
      } else {
        return obj;
      }
    };
    callable_ctor.__proto__ = ctor;
    callable_ctor.prototype = ctor.prototype;
    _ref = Function.prototype, callable_ctor.prototype.call = _ref.call, callable_ctor.prototype.apply = _ref.apply;
    return callable_ctor;
  };

  getattr = function() {
    var Ressource;
    debug('getattr');
    Ressource = require('./Ressource').Ressource;
    return Ressource;
  };

  module.exports.RessourceAttributesMixin = (function() {
    function RessourceAttributesMixin() {
      debug('constructor');
      this.getattr = callable(getattr);
      return this.getattr;
    }

    return RessourceAttributesMixin;

  })();

}).call(this);
