// Generated by CoffeeScript 1.6.3
(function() {
  var BaseSerializer, JsonSerializer, SERIALIZERS, YamlSerializer, debug, yamljs, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  debug = require('debug')('slumber:Serializer');

  BaseSerializer = (function() {
    BaseSerializer.prototype.content_types = null;

    BaseSerializer.prototype.key = null;

    function BaseSerializer() {
      this.dumps = __bind(this.dumps, this);
      this.loads = __bind(this.loads, this);
      this.get_content_type = __bind(this.get_content_type, this);
      this.debug = require('debug')("slumber:" + this.constructor.name);
      this.debug('constructor');
    }

    BaseSerializer.prototype.get_content_type = function() {
      if (this.content_types == null) {
        throw 'Not Implemented';
      }
      return this.content_types[0];
    };

    BaseSerializer.prototype.loads = function(data) {
      throw 'Not Implemented';
    };

    BaseSerializer.prototype.dumps = function(data) {
      throw 'Not Implemented';
    };

    return BaseSerializer;

  })();

  SERIALIZERS = module.exports.SERIALIZERS = {};

  JsonSerializer = (function(_super) {
    __extends(JsonSerializer, _super);

    function JsonSerializer() {
      this.dumps = __bind(this.dumps, this);
      this.loads = __bind(this.loads, this);
      _ref = JsonSerializer.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    JsonSerializer.prototype.content_types = ['application/json', 'application/x-javascript', 'text/javascript', 'text/x-javascript', 'text/x-json'];

    JsonSerializer.prototype.key = 'json';

    JsonSerializer.prototype.loads = function(data) {
      return JSON.parse(data);
    };

    JsonSerializer.prototype.dumps = function(data) {
      return JSON.stringify(data);
    };

    return JsonSerializer;

  })(BaseSerializer);

  SERIALIZERS.json = JsonSerializer;

  try {
    yamljs = require('yamljs');
    YamlSerializer = (function(_super) {
      __extends(YamlSerializer, _super);

      function YamlSerializer() {
        this.dumps = __bind(this.dumps, this);
        this.loads = __bind(this.loads, this);
        _ref1 = YamlSerializer.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      YamlSerializer.prototype.content_types = ['text/yaml'];

      YamlSerializer.prototype.key = 'yaml';

      YamlSerializer.prototype.loads = function(data) {
        return yamljs.parse(data);
      };

      YamlSerializer.prototype.dumps = function(data) {
        return yamljs.stringify(data);
      };

      return YamlSerializer;

    })(BaseSerializer);
    SERIALIZERS.yaml = YamlSerializer;
  } catch (_error) {}

  module.exports.Serializer = (function() {
    function Serializer(_default, serializers) {
      var key, obj, serializer, _i, _len;
      this["default"] = _default != null ? _default : 'json';
      if (serializers == null) {
        serializers = null;
      }
      this.get_content_type = __bind(this.get_content_type, this);
      this.dumps = __bind(this.dumps, this);
      this.loads = __bind(this.loads, this);
      this.get_serializer = __bind(this.get_serializer, this);
      debug('constructor', "@default=" + this["default"], "serializers=" + serializers);
      if (serializers == null) {
        serializers = [
          (function() {
            var _results;
            _results = [];
            for (key in SERIALIZERS) {
              obj = SERIALIZERS[key];
              _results.push(new obj);
            }
            return _results;
          })()
        ][0];
      }
      if (!serializers) {
        throw 'There are no available serializers.';
      }
      this.serializers = {};
      for (_i = 0, _len = serializers.length; _i < _len; _i++) {
        serializer = serializers[_i];
        this.serializers[serializer.key] = serializer;
      }
    }

    Serializer.prototype.get_serializer = function(name, content_type) {
      var ctype, serializer, serializer_name, _i, _len, _ref2, _ref3;
      if (name == null) {
        name = null;
      }
      if (content_type == null) {
        content_type = null;
      }
      if (name === null && content_type === null) {
        return this.serializers[this["default"]];
      }
      if (name != null) {
        if (this.serializers[name] == null) {
          throw "" + name + " is not an available serializer";
        }
        return this.serializers[name];
      }
      if (content_type != null) {
        _ref2 = this.serializers;
        for (serializer_name in _ref2) {
          serializer = _ref2[serializer_name];
          _ref3 = serializer.content_types;
          for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
            ctype = _ref3[_i];
            if (content_type === ctype) {
              return serializer;
            }
          }
        }
        throw "there is no available serializer for content-type " + content_type;
      }
    };

    Serializer.prototype.loads = function(data, format) {
      var s;
      if (format == null) {
        format = null;
      }
      s = this.get_serializer(format);
      return s.loads(data);
    };

    Serializer.prototype.dumps = function(data, format) {
      var s;
      if (format == null) {
        format = null;
      }
      s = this.get_serializer(format);
      return s.dumps(data);
    };

    Serializer.prototype.get_content_type = function(format) {
      var s;
      if (format == null) {
        format = null;
      }
      s = this.get_serializer(format);
      return s.get_content_type();
    };

    return Serializer;

  })();

}).call(this);
