// Generated by CoffeeScript 1.6.3
(function() {
  var debug,
    __slice = [].slice;

  debug = require('debug')('slumber:utils');

  module.exports.callable = function(ctor) {
    var callable_ctor, _ref;
    callable_ctor = function() {
      var a, obj, result;
      a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      obj = function() {
        return obj.callable.apply(obj, arguments);
      };
      obj.__proto__ = ctor.prototype;
      result = ctor.call.apply(ctor, [obj].concat(__slice.call(a)));
      if (typeof result === 'object') {
        return result;
      } else {
        return obj;
      }
    };
    callable_ctor.__proto__ = ctor;
    callable_ctor.prototype = ctor.prototype;
    _ref = Function.prototype, callable_ctor.prototype.call = _ref.call, callable_ctor.prototype.apply = _ref.apply;
    return callable_ctor;
  };

  module.exports.append_slash = function(str) {
    return str.replace(/\/$/, '') + '/';
  };

}).call(this);
