// Generated by CoffeeScript 1.12.0
(function() {
  var api, fs, slumber;

  fs = require('fs');

  slumber = require('..');

  api = slumber.API('http://httpbin.org/', {}, function() {
    var data;
    data = {
      headers: {
        "content-type": "application/x-www-form-urlencoded"
      },
      string: 'hello world',
      buffer: new Buffer([1, 2, 3]),
      number: 42,
      attachments: [fs.createReadStream(__dirname + "/post-file.coffee"), fs.createReadStream(__dirname + "/post-file.js")],
      custom_file: {
        value: fs.createReadStream("/dev/urandom"),
        options: {
          filename: "topsecret.jpg",
          contentType: "image/jpg"
        }
      }
    };
    return api('post').postForm(data, function(ret) {
      return console.log(ret);
    });
  });

}).call(this);
